export const seedQuizzes = [
  {
    title: 'Mathematics Fundamentals',
    description: 'Test your math skills from basic to advanced',
    category: 'Math',
    difficulty: 'mixed',
    timePerQuestion: 30,
    isPublic: true,
    questions: [
      {
        question: 'What is the value of π (pi) rounded to 2 decimal places?',
        options: ['3.12', '3.14', '3.16', '3.18'],
        correctAnswer: 1,
        explanation: 'Pi (π) ≈ 3.14159..., rounded to 2 decimal places is 3.14',
        difficulty: 'easy',
        points: 100,
      },
      {
        question: 'If a triangle has angles of 45°, 45°, and 90°, what type of triangle is it?',
        options: ['Equilateral', 'Scalene', 'Isosceles right triangle', 'Obtuse triangle'],
        correctAnswer: 2,
        explanation: 'A 45-45-90 triangle is an isosceles right triangle with two equal angles',
        difficulty: 'easy',
        points: 100,
      },
      {
        question: 'What is the derivative of x² + 3x + 5?',
        options: ['2x + 3', 'x² + 3', '2x + 5', 'x + 3'],
        correctAnswer: 0,
        explanation: 'd/dx(x²) = 2x, d/dx(3x) = 3, d/dx(5) = 0, so total is 2x + 3',
        difficulty: 'medium',
        points: 150,
      },
      {
        question: 'What is the sum of all integers from 1 to 100?',
        options: ['4950', '5000', '5050', '5100'],
        correctAnswer: 2,
        explanation: 'Using formula n(n+1)/2 = 100×101/2 = 5050',
        difficulty: 'medium',
        points: 150,
      },
      {
        question: 'If 2^x = 64, what is x?',
        options: ['5', '6', '7', '8'],
        correctAnswer: 1,
        explanation: '2^6 = 64, so x = 6',
        difficulty: 'medium',
        points: 150,
      },
      {
        question: 'What is the probability of getting 2 heads in 3 coin flips?',
        options: ['1/4', '3/8', '1/2', '5/8'],
        correctAnswer: 1,
        explanation: 'P = C(3,2) × (0.5)² × (0.5)¹ = 3 × 0.125 = 3/8',
        difficulty: 'hard',
        points: 200,
      },
      {
        question: 'What is the integral of sin(x)?',
        options: ['cos(x) + C', '-cos(x) + C', 'sin(x) + C', '-sin(x) + C'],
        correctAnswer: 1,
        explanation: 'The integral of sin(x) dx = -cos(x) + C',
        difficulty: 'hard',
        points: 200,
      },
    ],
  },
  {
    title: 'General Knowledge Challenge',
    description: 'How well do you know the world around you?',
    category: 'GK',
    difficulty: 'mixed',
    timePerQuestion: 25,
    isPublic: true,
    questions: [
      {
        question: 'Which country has the largest land area in the world?',
        options: ['Canada', 'China', 'United States', 'Russia'],
        correctAnswer: 3,
        explanation: 'Russia covers about 17.1 million km², making it the largest country by land area',
        difficulty: 'easy',
        points: 100,
      },
      {
        question: 'What is the chemical symbol for gold?',
        options: ['Go', 'Gd', 'Au', 'Ag'],
        correctAnswer: 2,
        explanation: 'Gold\'s chemical symbol is Au, from the Latin word "Aurum"',
        difficulty: 'easy',
        points: 100,
      },
      {
        question: 'Who painted the Mona Lisa?',
        options: ['Michelangelo', 'Raphael', 'Leonardo da Vinci', 'Donatello'],
        correctAnswer: 2,
        explanation: 'Leonardo da Vinci painted the Mona Lisa between 1503-1519',
        difficulty: 'easy',
        points: 100,
      },
      {
        question: 'Which ocean is the deepest?',
        options: ['Atlantic Ocean', 'Pacific Ocean', 'Indian Ocean', 'Arctic Ocean'],
        correctAnswer: 1,
        explanation: 'The Pacific Ocean contains the Mariana Trench, the deepest point on Earth',
        difficulty: 'medium',
        points: 150,
      },
      {
        question: 'In which year did World War II end?',
        options: ['1943', '1944', '1945', '1946'],
        correctAnswer: 2,
        explanation: 'World War II ended in 1945 with Germany surrendering in May and Japan in September',
        difficulty: 'medium',
        points: 150,
      },
      {
        question: 'Which element has the atomic number 1?',
        options: ['Helium', 'Carbon', 'Hydrogen', 'Oxygen'],
        correctAnswer: 2,
        explanation: 'Hydrogen is the lightest element with atomic number 1',
        difficulty: 'easy',
        points: 100,
      },
    ],
  },

  {
    title: 'Science Exploration',
    description: 'Discover the wonders of physics, chemistry, and biology',
    category: 'Science',
    difficulty: 'mixed',
    timePerQuestion: 30,
    isPublic: true,
    questions: [
      {
        question: 'What is the speed of light in a vacuum?',
        options: ['300,000 km/s', '150,000 km/s', '450,000 km/s', '600,000 km/s'],
        correctAnswer: 0,
        explanation: 'The speed of light in a vacuum is approximately 299,792 km/s, ~300,000 km/s',
        difficulty: 'easy',
        points: 100,
      },
      {
        question: 'What is DNA made of?',
        options: ['Amino acids', 'Nucleotides', 'Proteins', 'Lipids'],
        correctAnswer: 1,
        explanation: 'DNA is made of nucleotides, each containing a sugar, phosphate group, and nitrogenous base',
        difficulty: 'easy',
        points: 100,
      },
      {
        question: 'What is Newton\'s Second Law of Motion?',
        options: ['F = ma', 'E = mc²', 'PV = nRT', 'F = Gm₁m₂/r²'],
        correctAnswer: 0,
        explanation: "Newton's Second Law: Force equals mass times acceleration (F = ma)",
        difficulty: 'easy',
        points: 100,
      },
      {
        question: 'What is the powerhouse of the cell?',
        options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Endoplasmic Reticulum'],
        correctAnswer: 2,
        explanation: 'Mitochondria produce ATP through cellular respiration, earning the nickname "powerhouse of the cell"',
        difficulty: 'easy',
        points: 100,
      },
      {
        question: 'What is the pH of pure water?',
        options: ['6', '7', '8', '9'],
        correctAnswer: 1,
        explanation: 'Pure water has a neutral pH of exactly 7 at 25°C',
        difficulty: 'easy',
        points: 100,
      },
      {
        question: 'Which particle has a negative charge?',
        options: ['Proton', 'Neutron', 'Electron', 'Positron'],
        correctAnswer: 2,
        explanation: 'Electrons carry a negative charge of -1.6 × 10⁻¹⁹ coulombs',
        difficulty: 'easy',
        points: 100,
      },
      {
        question: 'What is Schrödinger\'s Cat thought experiment about?',
        options: [
          'Quantum superposition and measurement',
          'Relativity and time dilation',
          'Black hole information paradox',
          'Electromagnetic wave-particle duality',
        ],
        correctAnswer: 0,
        explanation: "Schrödinger's Cat illustrates quantum superposition - a system exists in multiple states until observed",
        difficulty: 'hard',
        points: 200,
      },
    ],
  },
];








